import { Roboto_Condensed, Cairo } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from "@/context/quizzContext";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";
import Loading from "./loading";

const roboto = Roboto_Condensed({
  subsets: ["latin"],

});
const cairo = Cairo({
  subsets: ["latin"],
});

export const metadata = {
  title: "Quizziy😎",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
        <MyContextProvider>
          <Toaster />
          <Suspense fallback={<Loading />}>
            {children}</Suspense>
        </MyContextProvider>
      </body>
    </html>
  );
}
