import { Roboto_Condensed, Cairo } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from "@/context/quizzContext";


const roboto = Roboto_Condensed({
  subsets: ["latin"],

});
const cairo = Cairo({

  subsets: ["latin"],
});

export const metadata = {
  title: "Quizziy😎",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}  `}
      >
        <MyContextProvider>
          {children}
        </MyContextProvider>
      </body>
    </html>
  );
}
